version: '2'
services:
  dwc2-klipper-cr10s:
    image: "stevenvo/dwc2-klipper:arm"
    container_name: cr10s
    privileged: true
    ports:
      - "4750:4750"
    volumes:
      - "/home/pi/cr10s-klipper-printer.cfg:/home/dwc2-klipper/config"
      - /dev:/dev
    environment:
      TZ: America/Los_Angeles
    restart: unless-stopped

  dwc2-klipper-ender3:
    image: "stevenvo/dwc2-klipper:arm"
    container_name: ender3
    privileged: true
    ports:
      - "4751:4750"
    volumes:
      - "/home/pi/ender3-klipper-printer.cfg:/home/dwc2-klipper/config"
      - /dev:/dev
    environment:
      TZ: America/Los_Angeles
    restart: unless-stopped
    
  dwc2-klipper-kossel:
    image: "stevenvo/dwc2-klipper:arm"
    container_name: kossel
    privileged: true
    ports:
      - "4752:4750"
    volumes:
      - "/home/pi/kossel-klipper-printer.cfg:/home/dwc2-klipper/config"
      - /dev:/dev
    environment:
      TZ: America/Los_Angeles
    restart: unless-stopped